# https://firefox-source-docs.mozilla.org/setup/linux_build.html
name: Build Firefox for Linux

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Maximize build space
              uses: easimon/maximize-build-space@c28619d8999a147d5e09c1199f84ff6af6ad5794
              with:
                  root-reserve-mb: 15360
                  swap-size-mb: 1024
                  remove-dotnet: "true"
                  remove-android: "true"
                  remove-haskell: "true"
                  remove-codeql: "true"
                  remove-docker-images: "true"

            - name: Bootstrap a copy of the Firefox source code
              uses: actions/checkout@v5
              with:
                  repository: "mozilla-firefox/firefox"

            - name: System preparation
              run: sudo apt-get update && sudo apt-get install curl python3 python3-pip git

            - name: Bootstrap
              run: ./mach --no-interactive bootstrap --application-choice browser
              # browser_artifact_mode or browser, browser for full build

            - name: Check free space
              run: |
                  echo "Free space:"
                  df -h

            - name: Build
              run: ./mach --no-interactive build

            - name: Build symbols
              run: ./mach --no-interactive buildsymbols

            - name: Package
              run: ./mach --no-interactive package

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: dist
                  path: obj-x86_64-pc-linux-gnu/dist/
                  compression-level: 9

            - name: System preparation for testing
              run: sudo apt-get update && sudo apt-get install ubuntu-desktop

            # To get your tests running in continuous integration, try web-platform-tests, or Mochitest.
            # - name: Testing - web-platform-tests
            #   continue-on-error: true
            #   run: ./mach --no-interactive wpt --headless

            - name: Testing - mochitest
              continue-on-error: true
              run: ./mach --no-interactive mochitest --headless
